name: Run Katalon Tests

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch:

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Download and Extract Katalon Studio
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Linux_64-8.6.5.tar.gz
          mkdir katalon
          tar -xzf Katalon_Studio_Linux_64-8.6.5.tar.gz -C katalon --strip-components=1
          chmod +x katalon/katalonc

      - name: Run Katalon Test
        run: |
          ./katalon/katalonc -noSplash \
          -runMode=console \
          -projectPath="$(pwd)/parabank.prj" \
          -testSuitePath="Test Suites/New Test Suite" \
          -browserType="Chrome" \
          -apiKey="${{ secrets.KATALON_API_KEY }}"
