name: Run Katalon Tests

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST (3:30 UTC)
  workflow_dispatch:      # Enables manual "Run workflow" button

jobs:
  katalon-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'       # ✅ FIX: Required field
          java-version: '8'             # Java 8 for Katalon compatibility

      - name: Download Katalon Studio
        run: |
          wget https://github.com/katalon-studio/katalon-studio/releases/download/v8.6.5/Katalon_Studio_Linux_64-8.6.5.tar.gz
          tar -xzf Katalon_Studio_Linux_64-8.6.5.tar.gz
          chmod +x Katalon_Studio_Linux_64-8.6.5/katalonc

      - name: Run Katalon test
        run: |
          ./Katalon_Studio_Linux_64-8.6.5/katalonc -noSplash \
          -runMode=console \
          -projectPath="$(pwd)/parabank.prj" \
          -testSuitePath="Test Suites/New Test Suite" \
          -browserType="Chrome" \
          -apiKey="${{ secrets.KATALON_API_KEY }}"
